# Generated by Django 3.1.1 on 2020-09-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_clean_air", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measuringdata",
            old_name="sensor",
            new_name="sensors",
        ),
        migrations.RenameField(
            model_name="measuringstands",
            old_name="index",
            new_name="indexes",
        ),
        migrations.RenameField(
            model_name="measuringstands",
            old_name="station",
            new_name="stations",
        ),
        migrations.RenameField(
            model_name="measuringstation",
            old_name="city",
            new_name="cities",
        ),
    ]
