# Generated by Django 3.1.1 on 2020-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_clean_air", "0002_auto_20200930_0826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuringdata",
            name="date",
            field=models.DateTimeField(verbose_name="date"),
        ),
    ]
