# Generated by Django 3.1.1 on 2020-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_clean_air", "0003_auto_20200930_0834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuringdata",
            name="value",
            field=models.FloatField(blank=True, null=True, verbose_name="value"),
        ),
    ]
